# Generated by Django 3.2.24 on 2025-09-19 08:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Configuration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('config_name', models.CharField(default='default', max_length=100)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Main Configuration',
                'verbose_name_plural': 'Main Confiugrations',
            },
        ),
        migrations.CreateModel(
            name='LangLocale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('shortcode', models.CharField(choices=[('am', 'Amharic'), ('en', 'English'), ('orm', 'Afaan Oromia'), ('fr', 'French')], max_length=10, unique=True)),
                ('logo', models.FileField(null=True, upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='FrontPageImageConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.FileField(upload_to='')),
                ('desktop_image', models.ImageField(blank=True, null=True, upload_to='banners/desktop')),
                ('tablet_image', models.ImageField(blank=True, null=True, upload_to='banners/tablet')),
                ('mobile_image', models.ImageField(blank=True, null=True, upload_to='banners/mobile')),
                ('cta_text', models.CharField(blank=True, max_length=150)),
                ('cta_link', models.URLField(blank=True, null=True)),
                ('order', models.IntegerField(default=0)),
                ('image_location', models.PositiveSmallIntegerField(choices=[(1, 'Main Banner'), (2, 'Side Banner'), (3, 'Casino Banner'), (4, 'Popup Banner'), (5, 'Login Banner'), (6, 'Sign-Up Banner'), (7, 'Deposit Banner'), (8, 'Mobile Header Banner')], default=1)),
                ('image_channel', models.PositiveSmallIntegerField(choices=[(1, 'Desktop'), (2, 'Mobile'), (3, 'Both')], default=3)),
                ('provider', models.PositiveSmallIntegerField(choices=[(1, 'Casino'), (2, 'Sport'), (3, 'Both')], default=3)),
                ('image_link', models.CharField(blank=True, max_length=150)),
                ('transition_type', models.CharField(choices=[('none', 'none'), ('fade', 'fade'), ('slide', 'slide'), ('zoom', 'zoom')], default='none', max_length=50)),
                ('transition_duration', models.PositiveIntegerField(default=300)),
                ('start_time', models.DateTimeField(blank=True, null=True)),
                ('end_time', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('configuration', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='front_page_images', to='banners.configuration')),
                ('locale', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='banner_images', to='banners.langlocale')),
            ],
            options={
                'ordering': ('order',),
            },
        ),
    ]
