# Generated by Django 3.2.24 on 2025-09-19 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banners', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='frontpageimageconfiguration',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
