# Generated by Django 3.2.24 on 2025-09-19 10:18

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banners', '0002_frontpageimageconfiguration_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='frontpageimageconfiguration',
            name='photo',
            field=models.FileField(upload_to='banners/original', validators=[django.core.validators.FileExtensionValidator(['jpg', 'jpeg', 'png'])]),
        ),
    ]
