# Generated by Django 3.2.24 on 2025-09-22 08:16

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banners', '0003_alter_frontpageimageconfiguration_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='frontpageimageconfiguration',
            name='photo',
            field=models.FileField(upload_to='banners/original', validators=[django.core.validators.FileExtensionValidator(['jpg', 'jpeg', 'png', 'webp'])]),
        ),
    ]
